// Generated 2026-04-12T07:56:56.638436 by generate_data.py
const LABOR = {
  "meta": {
    "generated": "2026-04-12T07:56:56.638112",
    "totalStatements": 3253,
    "totalPapers": 2368,
    "laborStatements": 2304,
    "laborPapers": 1117,
    "themes": 17,
    "regions": 12
  },
  "summary": {
    "totalItems": 3421,
    "totalDocuments": 3421,
    "statementsCount": 2304,
    "totalStatements": 2304,
    "papersCount": 1117,
    "totalPapers": 1117,
    "regionsRepresented": 12,
    "totalRegions": 12,
    "totalCountries": 218,
    "totalThemes": 17,
    "yearRange": [
      1998,
      2026
    ],
    "dateRange": "1998\u20132026",
    "dateRangeDetail": "1998 to 2026",
    "topThemes": {
      "labels": [
        "Automation & Displacement",
        "Creative, Knowledge & Content Labor",
        "Collective Bargaining & Social Dialogue",
        "Disability, Accessibility & Assistive AI",
        "Informal Economy & Global Labor Supply Chains",
        "Skill Transformation (De/Up/Reskilling)",
        "Just Transition & Policy Futures",
        "Economic Inequality & Wage Dynamics",
        "Gendered Labor & Care Work",
        "Task Augmentation & Productivity",
        "Data Annotation & HITL Labor",
        "Cross-Cutting / Unspecified",
        "Algorithmic Management & Decision-Making",
        "Public Sector AI & Digital Government",
        "Dignity of Work & Human Flourishing",
        "Content Moderation & Trust/Safety",
        "Worker Surveillance & Monitoring"
      ],
      "values": [
        897,
        853,
        610,
        599,
        538,
        513,
        486,
        471,
        463,
        419,
        385,
        342,
        318,
        295,
        243,
        225,
        117
      ]
    },
    "topRegions": {
      "labels": [
        "Global/International",
        "North America",
        "Europe (Western)",
        "UK & Ireland",
        "East Asia",
        "Middle East & North Africa",
        "Sub-Saharan Africa",
        "Southeast Asia",
        "Oceania",
        "Latin America & Caribbean",
        "Europe (Central/Eastern)",
        "South Asia"
      ],
      "values": [
        1479,
        667,
        381,
        221,
        149,
        92,
        83,
        82,
        77,
        73,
        63,
        54
      ]
    },
    "sourceBreakdown": {
      "labels": [
        "Statements",
        "Papers"
      ],
      "values": [
        2304,
        1117
      ]
    },
    "keyFindings": [
      "3421 labor-relevant items identified across 12 regions (2304 policy statements, 1117 academic papers).",
      "\"Automation & Displacement\" dominates with 897 items (26.2% of corpus).",
      "Global/International has the highest concentration of labor discourse (1479 items).",
      "The gap between statements and papers is most pronounced in \"Creative, Knowledge & Content Labor\" (703 statements vs. 150 papers).",
      "Voice gap: South Asia (discussed in 164 items vs. 54 authored); East Asia (discussed in 412 items vs. 149 authored); Europe (Central/Eastern) (discussed in 147 items vs. 63 authored) \u2014 these regions are frequently discussed in labor & AI literature but produce relatively few items themselves.",
      "52 items reference Catholic Social Teaching documents (Laudato Si', Rerum Novarum, etc.).",
      "2610 items (76.3% of total) were published from 2023 onward, reflecting post-ChatGPT acceleration.",
      "\"Worker Surveillance & Monitoring\" is the least-covered theme with only 117 items."
    ]
  },
  "heatmap": {
    "regions": [
      "North America",
      "Europe (Western)",
      "Europe (Central/Eastern)",
      "UK & Ireland",
      "Oceania",
      "East Asia",
      "South Asia",
      "Southeast Asia",
      "Middle East & North Africa",
      "Sub-Saharan Africa",
      "Latin America & Caribbean",
      "Global/International"
    ],
    "themes": [
      "Automation & Displacement",
      "Task Augmentation & Productivity",
      "Data Annotation & HITL Labor",
      "Content Moderation & Trust/Safety",
      "Creative, Knowledge & Content Labor",
      "Worker Surveillance & Monitoring",
      "Algorithmic Management & Decision-Making",
      "Skill Transformation (De/Up/Reskilling)",
      "Dignity of Work & Human Flourishing",
      "Economic Inequality & Wage Dynamics",
      "Collective Bargaining & Social Dialogue",
      "Gendered Labor & Care Work",
      "Informal Economy & Global Labor Supply Chains",
      "Disability, Accessibility & Assistive AI",
      "Just Transition & Policy Futures",
      "Public Sector AI & Digital Government",
      "Cross-Cutting / Unspecified"
    ],
    "themeKeys": [
      "automation_displacement",
      "task_augmentation",
      "data_annotation_hitl",
      "content_moderation",
      "creative_knowledge",
      "surveillance",
      "algorithmic_management",
      "skill_transformation",
      "dignity_of_work",
      "economic_inequality",
      "collective_bargaining",
      "gendered_labor",
      "informal_supply_chains",
      "disability_accessibility",
      "just_transition",
      "public_sector_ai",
      "cross_cutting"
    ],
    "matrix": [
      [
        200,
        117,
        23,
        42,
        228,
        46,
        108,
        99,
        49,
        84,
        104,
        89,
        122,
        151,
        85,
        39,
        64
      ],
      [
        97,
        53,
        11,
        10,
        93,
        31,
        44,
        63,
        36,
        35,
        142,
        30,
        76,
        59,
        64,
        53,
        26
      ],
      [
        17,
        4,
        0,
        0,
        10,
        0,
        5,
        25,
        5,
        7,
        31,
        7,
        6,
        16,
        15,
        27,
        4
      ],
      [
        63,
        44,
        10,
        10,
        91,
        13,
        34,
        37,
        13,
        28,
        43,
        20,
        52,
        54,
        20,
        38,
        12
      ],
      [
        25,
        19,
        2,
        1,
        31,
        2,
        16,
        9,
        1,
        8,
        11,
        8,
        17,
        24,
        9,
        18,
        5
      ],
      [
        17,
        21,
        8,
        4,
        48,
        1,
        9,
        32,
        24,
        24,
        22,
        13,
        27,
        21,
        45,
        10,
        16
      ],
      [
        7,
        13,
        0,
        2,
        21,
        1,
        5,
        20,
        3,
        8,
        13,
        2,
        7,
        14,
        24,
        8,
        3
      ],
      [
        19,
        23,
        7,
        0,
        24,
        1,
        9,
        32,
        9,
        13,
        15,
        17,
        14,
        16,
        25,
        11,
        4
      ],
      [
        12,
        12,
        1,
        4,
        21,
        1,
        4,
        32,
        7,
        14,
        17,
        7,
        12,
        14,
        30,
        16,
        10
      ],
      [
        17,
        17,
        6,
        11,
        13,
        4,
        6,
        42,
        12,
        30,
        34,
        22,
        27,
        30,
        35,
        16,
        1
      ],
      [
        14,
        13,
        1,
        1,
        16,
        2,
        8,
        15,
        8,
        10,
        10,
        12,
        10,
        5,
        18,
        10,
        8
      ],
      [
        409,
        83,
        316,
        140,
        257,
        15,
        70,
        107,
        76,
        210,
        168,
        236,
        168,
        195,
        116,
        49,
        189
      ]
    ],
    "rowTotals": [
      1650,
      923,
      179,
      582,
      206,
      342,
      151,
      239,
      214,
      323,
      161,
      2804
    ],
    "colTotals": [
      897,
      419,
      385,
      225,
      853,
      117,
      318,
      513,
      243,
      471,
      610,
      463,
      538,
      599,
      486,
      295,
      342
    ],
    "matrixNormalized": [
      [
        12.1,
        7.1,
        1.4,
        2.5,
        13.8,
        2.8,
        6.5,
        6.0,
        3.0,
        5.1,
        6.3,
        5.4,
        7.4,
        9.2,
        5.2,
        2.4,
        3.9
      ],
      [
        10.5,
        5.7,
        1.2,
        1.1,
        10.1,
        3.4,
        4.8,
        6.8,
        3.9,
        3.8,
        15.4,
        3.3,
        8.2,
        6.4,
        6.9,
        5.7,
        2.8
      ],
      [
        9.5,
        2.2,
        0.0,
        0.0,
        5.6,
        0.0,
        2.8,
        14.0,
        2.8,
        3.9,
        17.3,
        3.9,
        3.4,
        8.9,
        8.4,
        15.1,
        2.2
      ],
      [
        10.8,
        7.6,
        1.7,
        1.7,
        15.6,
        2.2,
        5.8,
        6.4,
        2.2,
        4.8,
        7.4,
        3.4,
        8.9,
        9.3,
        3.4,
        6.5,
        2.1
      ],
      [
        12.1,
        9.2,
        1.0,
        0.5,
        15.0,
        1.0,
        7.8,
        4.4,
        0.5,
        3.9,
        5.3,
        3.9,
        8.3,
        11.7,
        4.4,
        8.7,
        2.4
      ],
      [
        5.0,
        6.1,
        2.3,
        1.2,
        14.0,
        0.3,
        2.6,
        9.4,
        7.0,
        7.0,
        6.4,
        3.8,
        7.9,
        6.1,
        13.2,
        2.9,
        4.7
      ],
      [
        4.6,
        8.6,
        0.0,
        1.3,
        13.9,
        0.7,
        3.3,
        13.2,
        2.0,
        5.3,
        8.6,
        1.3,
        4.6,
        9.3,
        15.9,
        5.3,
        2.0
      ],
      [
        7.9,
        9.6,
        2.9,
        0.0,
        10.0,
        0.4,
        3.8,
        13.4,
        3.8,
        5.4,
        6.3,
        7.1,
        5.9,
        6.7,
        10.5,
        4.6,
        1.7
      ],
      [
        5.6,
        5.6,
        0.5,
        1.9,
        9.8,
        0.5,
        1.9,
        15.0,
        3.3,
        6.5,
        7.9,
        3.3,
        5.6,
        6.5,
        14.0,
        7.5,
        4.7
      ],
      [
        5.3,
        5.3,
        1.9,
        3.4,
        4.0,
        1.2,
        1.9,
        13.0,
        3.7,
        9.3,
        10.5,
        6.8,
        8.4,
        9.3,
        10.8,
        5.0,
        0.3
      ],
      [
        8.7,
        8.1,
        0.6,
        0.6,
        9.9,
        1.2,
        5.0,
        9.3,
        5.0,
        6.2,
        6.2,
        7.5,
        6.2,
        3.1,
        11.2,
        6.2,
        5.0
      ],
      [
        14.6,
        3.0,
        11.3,
        5.0,
        9.2,
        0.5,
        2.5,
        3.8,
        2.7,
        7.5,
        6.0,
        8.4,
        6.0,
        7.0,
        4.1,
        1.7,
        6.7
      ]
    ],
    "colNormalized": [
      [
        22.3,
        27.9,
        6.0,
        18.7,
        26.7,
        39.3,
        34.0,
        19.3,
        20.2,
        17.8,
        17.0,
        19.2,
        22.7,
        25.2,
        17.5,
        13.2,
        18.7
      ],
      [
        10.8,
        12.6,
        2.9,
        4.4,
        10.9,
        26.5,
        13.8,
        12.3,
        14.8,
        7.4,
        23.3,
        6.5,
        14.1,
        9.8,
        13.2,
        18.0,
        7.6
      ],
      [
        1.9,
        1.0,
        0.0,
        0.0,
        1.2,
        0.0,
        1.6,
        4.9,
        2.1,
        1.5,
        5.1,
        1.5,
        1.1,
        2.7,
        3.1,
        9.2,
        1.2
      ],
      [
        7.0,
        10.5,
        2.6,
        4.4,
        10.7,
        11.1,
        10.7,
        7.2,
        5.3,
        5.9,
        7.0,
        4.3,
        9.7,
        9.0,
        4.1,
        12.9,
        3.5
      ],
      [
        2.8,
        4.5,
        0.5,
        0.4,
        3.6,
        1.7,
        5.0,
        1.8,
        0.4,
        1.7,
        1.8,
        1.7,
        3.2,
        4.0,
        1.9,
        6.1,
        1.5
      ],
      [
        1.9,
        5.0,
        2.1,
        1.8,
        5.6,
        0.9,
        2.8,
        6.2,
        9.9,
        5.1,
        3.6,
        2.8,
        5.0,
        3.5,
        9.3,
        3.4,
        4.7
      ],
      [
        0.8,
        3.1,
        0.0,
        0.9,
        2.5,
        0.9,
        1.6,
        3.9,
        1.2,
        1.7,
        2.1,
        0.4,
        1.3,
        2.3,
        4.9,
        2.7,
        0.9
      ],
      [
        2.1,
        5.5,
        1.8,
        0.0,
        2.8,
        0.9,
        2.8,
        6.2,
        3.7,
        2.8,
        2.5,
        3.7,
        2.6,
        2.7,
        5.1,
        3.7,
        1.2
      ],
      [
        1.3,
        2.9,
        0.3,
        1.8,
        2.5,
        0.9,
        1.3,
        6.2,
        2.9,
        3.0,
        2.8,
        1.5,
        2.2,
        2.3,
        6.2,
        5.4,
        2.9
      ],
      [
        1.9,
        4.1,
        1.6,
        4.9,
        1.5,
        3.4,
        1.9,
        8.2,
        4.9,
        6.4,
        5.6,
        4.8,
        5.0,
        5.0,
        7.2,
        5.4,
        0.3
      ],
      [
        1.6,
        3.1,
        0.3,
        0.4,
        1.9,
        1.7,
        2.5,
        2.9,
        3.3,
        2.1,
        1.6,
        2.6,
        1.9,
        0.8,
        3.7,
        3.4,
        2.3
      ],
      [
        45.6,
        19.8,
        82.1,
        62.2,
        30.1,
        12.8,
        22.0,
        20.9,
        31.3,
        44.6,
        27.5,
        51.0,
        31.2,
        32.6,
        23.9,
        16.6,
        55.3
      ]
    ],
    "statementsMatrix": [
      [
        200,
        117,
        23,
        42,
        228,
        46,
        108,
        99,
        49,
        84,
        104,
        89,
        122,
        151,
        85,
        39,
        64
      ],
      [
        97,
        53,
        11,
        10,
        93,
        31,
        44,
        63,
        36,
        35,
        142,
        30,
        76,
        59,
        64,
        53,
        26
      ],
      [
        17,
        4,
        0,
        0,
        10,
        0,
        5,
        25,
        5,
        7,
        31,
        7,
        6,
        16,
        15,
        27,
        4
      ],
      [
        63,
        44,
        10,
        10,
        91,
        13,
        34,
        37,
        13,
        28,
        43,
        20,
        52,
        54,
        20,
        38,
        12
      ],
      [
        25,
        19,
        2,
        1,
        31,
        2,
        16,
        9,
        1,
        8,
        11,
        8,
        17,
        24,
        9,
        18,
        5
      ],
      [
        17,
        21,
        8,
        4,
        48,
        1,
        9,
        32,
        24,
        24,
        22,
        13,
        27,
        21,
        45,
        10,
        16
      ],
      [
        7,
        13,
        0,
        2,
        21,
        1,
        5,
        20,
        3,
        8,
        13,
        2,
        7,
        14,
        24,
        8,
        3
      ],
      [
        19,
        23,
        7,
        0,
        24,
        1,
        9,
        32,
        9,
        13,
        15,
        17,
        14,
        16,
        25,
        11,
        4
      ],
      [
        12,
        12,
        1,
        4,
        21,
        1,
        4,
        32,
        7,
        14,
        17,
        7,
        12,
        14,
        30,
        16,
        10
      ],
      [
        17,
        17,
        6,
        11,
        13,
        4,
        6,
        42,
        12,
        30,
        34,
        22,
        27,
        30,
        35,
        16,
        1
      ],
      [
        14,
        13,
        1,
        1,
        16,
        2,
        8,
        15,
        8,
        10,
        10,
        12,
        10,
        5,
        18,
        10,
        8
      ],
      [
        89,
        53,
        8,
        12,
        107,
        15,
        32,
        99,
        67,
        113,
        113,
        76,
        74,
        77,
        109,
        44,
        15
      ]
    ],
    "papersMatrix": [
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        320,
        30,
        308,
        128,
        150,
        0,
        38,
        8,
        9,
        97,
        55,
        160,
        94,
        118,
        7,
        5,
        174
      ]
    ]
  },
  "geographic": {
    "regionTotals": {
      "labels": [
        "Global/International",
        "North America",
        "Europe (Western)",
        "UK & Ireland",
        "East Asia",
        "Middle East & North Africa",
        "Sub-Saharan Africa",
        "Southeast Asia",
        "Oceania",
        "Latin America & Caribbean",
        "Europe (Central/Eastern)",
        "South Asia"
      ],
      "values": [
        1479,
        667,
        381,
        221,
        149,
        92,
        83,
        82,
        77,
        73,
        63,
        54
      ]
    },
    "countryTotals": [
      {
        "name": "United States",
        "value": 603
      },
      {
        "name": "N/A",
        "value": 504
      },
      {
        "name": "International",
        "value": 233
      },
      {
        "name": "United Kingdom",
        "value": 213
      },
      {
        "name": "Multicultural/Cross-cultural",
        "value": 113
      },
      {
        "name": "Indian",
        "value": 78
      },
      {
        "name": "Chinese",
        "value": 70
      },
      {
        "name": "Germany",
        "value": 69
      },
      {
        "name": "European Union",
        "value": 65
      },
      {
        "name": "Canada",
        "value": 64
      },
      {
        "name": "France",
        "value": 63
      },
      {
        "name": "Australia",
        "value": 59
      },
      {
        "name": "Belgium",
        "value": 57
      },
      {
        "name": "China",
        "value": 46
      },
      {
        "name": "South Korea",
        "value": 44
      },
      {
        "name": "India",
        "value": 43
      },
      {
        "name": "Japan",
        "value": 39
      },
      {
        "name": "Brazil",
        "value": 38
      },
      {
        "name": "Switzerland",
        "value": 36
      },
      {
        "name": "Arabic",
        "value": 36
      },
      {
        "name": "African/Ubuntu",
        "value": 35
      },
      {
        "name": "Netherlands",
        "value": 33
      },
      {
        "name": "United Nations",
        "value": 31
      },
      {
        "name": "Korean",
        "value": 25
      },
      {
        "name": "Singapore",
        "value": 24
      },
      {
        "name": "American",
        "value": 23
      },
      {
        "name": "Brazilian",
        "value": 20
      },
      {
        "name": "Iranian",
        "value": 20
      },
      {
        "name": "Spain",
        "value": 19
      },
      {
        "name": "Austria",
        "value": 19
      },
      {
        "name": "South Africa",
        "value": 18
      },
      {
        "name": "Italy",
        "value": 17
      },
      {
        "name": "German",
        "value": 17
      },
      {
        "name": "Finland",
        "value": 15
      },
      {
        "name": "New Zealand",
        "value": 15
      },
      {
        "name": "Kenya",
        "value": 15
      },
      {
        "name": "Indonesian",
        "value": 15
      },
      {
        "name": "Thailand",
        "value": 14
      },
      {
        "name": "Saudi Arabia",
        "value": 13
      },
      {
        "name": "Spanish",
        "value": 13
      },
      {
        "name": "Italian",
        "value": 13
      },
      {
        "name": "Japanese",
        "value": 13
      },
      {
        "name": "Israel",
        "value": 12
      },
      {
        "name": "Sweden",
        "value": 12
      },
      {
        "name": "Malaysia",
        "value": 12
      },
      {
        "name": "Norway",
        "value": 11
      },
      {
        "name": "Turkey",
        "value": 11
      },
      {
        "name": "Egypt",
        "value": 10
      },
      {
        "name": "Philippines",
        "value": 10
      },
      {
        "name": "Colombia",
        "value": 9
      }
    ],
    "regionBySource": {
      "regions": [
        "Global/International",
        "North America",
        "Europe (Western)",
        "UK & Ireland",
        "East Asia",
        "Middle East & North Africa",
        "Sub-Saharan Africa",
        "Southeast Asia",
        "Oceania",
        "Latin America & Caribbean",
        "Europe (Central/Eastern)",
        "South Asia"
      ],
      "statements": [
        362,
        667,
        381,
        221,
        149,
        92,
        83,
        82,
        77,
        73,
        63,
        54
      ],
      "papers": [
        1117,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "languageDistribution": {
      "labels": [
        "en",
        "English",
        "Multilingual",
        "Chinese",
        "es",
        "de",
        "ar",
        "fr",
        "pt",
        "zh",
        "Arabic",
        "Korean",
        "Portuguese",
        "ko",
        "Persian"
      ],
      "values": [
        2368,
        165,
        89,
        38,
        36,
        32,
        32,
        30,
        30,
        23,
        23,
        22,
        21,
        19,
        18
      ]
    }
  },
  "temporal": {
    "years": [
      1998,
      1999,
      2000,
      2001,
      2002,
      2003,
      2004,
      2005,
      2006,
      2007,
      2008,
      2009,
      2010,
      2011,
      2012,
      2013,
      2014,
      2015,
      2016,
      2017,
      2018,
      2019,
      2020,
      2021,
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "byTheme": {
      "automation_displacement": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        1,
        1,
        9,
        31,
        42,
        55,
        35,
        47,
        44,
        126,
        225,
        244,
        36
      ],
      "task_augmentation": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        14,
        18,
        31,
        10,
        27,
        8,
        51,
        109,
        132,
        16
      ],
      "data_annotation_hitl": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        15,
        11,
        11,
        21,
        60,
        106,
        140,
        16
      ],
      "content_moderation": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        8,
        1,
        4,
        9,
        11,
        32,
        62,
        88,
        10
      ],
      "creative_knowledge": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        2,
        4,
        18,
        19,
        26,
        31,
        35,
        151,
        262,
        274,
        29
      ],
      "surveillance": [
        0,
        2,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        2,
        7,
        11,
        8,
        16,
        31,
        30,
        3
      ],
      "algorithmic_management": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        2,
        13,
        13,
        22,
        19,
        27,
        18,
        47,
        70,
        75,
        11
      ],
      "skill_transformation": [
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        1,
        13,
        22,
        23,
        21,
        42,
        18,
        81,
        115,
        152,
        23
      ],
      "dignity_of_work": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        10,
        16,
        17,
        10,
        12,
        6,
        36,
        42,
        84,
        9
      ],
      "economic_inequality": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        3,
        5,
        10,
        28,
        14,
        27,
        16,
        59,
        140,
        155,
        12
      ],
      "collective_bargaining": [
        0,
        1,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        9,
        15,
        20,
        21,
        38,
        34,
        95,
        168,
        186,
        19
      ],
      "gendered_labor": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        1,
        19,
        17,
        18,
        26,
        19,
        68,
        126,
        151,
        16
      ],
      "informal_supply_chains": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        7,
        14,
        12,
        20,
        40,
        19,
        67,
        148,
        183,
        26
      ],
      "disability_accessibility": [
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        4,
        21,
        23,
        26,
        39,
        34,
        99,
        160,
        170,
        21
      ],
      "just_transition": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        3,
        10,
        24,
        36,
        19,
        36,
        21,
        67,
        113,
        143,
        12
      ],
      "public_sector_ai": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        3,
        12,
        22,
        22,
        29,
        16,
        40,
        76,
        68,
        5
      ],
      "cross_cutting": [
        1,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        1,
        14,
        14,
        8,
        12,
        16,
        40,
        100,
        121,
        12
      ]
    },
    "bySource": {
      "statements": [
        1,
        3,
        1,
        1,
        0,
        1,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        3,
        3,
        9,
        46,
        105,
        138,
        102,
        135,
        113,
        366,
        610,
        582,
        83
      ],
      "papers": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        16,
        16,
        25,
        35,
        54,
        117,
        305,
        510,
        37
      ]
    },
    "cumulative": {
      "years": [
        1998,
        1999,
        2000,
        2001,
        2002,
        2003,
        2004,
        2005,
        2006,
        2007,
        2008,
        2009,
        2010,
        2011,
        2012,
        2013,
        2014,
        2015,
        2016,
        2017,
        2018,
        2019,
        2020,
        2021,
        2022,
        2023,
        2024,
        2025,
        2026
      ],
      "total": [
        1,
        4,
        5,
        6,
        6,
        7,
        7,
        7,
        7,
        7,
        8,
        8,
        8,
        9,
        9,
        9,
        12,
        15,
        26,
        72,
        193,
        347,
        474,
        644,
        811,
        1294,
        2209,
        3301,
        3421
      ],
      "statements": [
        1,
        4,
        5,
        6,
        6,
        7,
        7,
        7,
        7,
        7,
        8,
        8,
        8,
        9,
        9,
        9,
        12,
        15,
        24,
        70,
        175,
        313,
        415,
        550,
        663,
        1029,
        1639,
        2221,
        2304
      ],
      "papers": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        2,
        18,
        34,
        59,
        94,
        148,
        265,
        570,
        1080,
        1117
      ]
    },
    "events": [
      {
        "year": 2022,
        "month": 8,
        "label": "Stable Diffusion release"
      },
      {
        "year": 2022,
        "month": 11,
        "label": "ChatGPT launch"
      },
      {
        "year": 2023,
        "month": 2,
        "label": "GPT-4 launch"
      },
      {
        "year": 2023,
        "month": 5,
        "label": "WGA strike begins"
      },
      {
        "year": 2023,
        "month": 7,
        "label": "SAG-AFTRA strike begins"
      },
      {
        "year": 2023,
        "month": 10,
        "label": "Biden AI Executive Order"
      },
      {
        "year": 2023,
        "month": 11,
        "label": "SAG-AFTRA deal reached"
      },
      {
        "year": 2023,
        "month": 12,
        "label": "NYT v. OpenAI filed"
      },
      {
        "year": 2024,
        "month": 3,
        "label": "EU AI Act final text"
      }
    ]
  },
  "voiceGap": {
    "orgTypes": {
      "labels": [
        "government",
        "civil_society",
        "intergovernmental",
        "professional",
        "industry",
        "religious",
        "labor",
        "academic",
        "national_ethics_body",
        "multistakeholder",
        "indigenous"
      ],
      "values": [
        666,
        488,
        265,
        264,
        171,
        125,
        92,
        91,
        76,
        54,
        12
      ]
    },
    "bindingNature": {
      "labels": [
        "advisory",
        "voluntary",
        "soft_law",
        "legally_binding",
        "aspirational"
      ],
      "values": [
        1199,
        544,
        240,
        164,
        157
      ]
    },
    "stmtTypes": {
      "labels": [
        "guidelines",
        "framework",
        "report",
        "position_paper",
        "statement",
        "declaration",
        "recommendation",
        "other",
        "legislation",
        "white_paper",
        "resolution",
        "standard",
        "regulation",
        "communique",
        "code_of_conduct"
      ],
      "values": [
        445,
        346,
        312,
        233,
        183,
        162,
        117,
        102,
        96,
        61,
        51,
        27,
        26,
        26,
        24
      ]
    },
    "affectedVsAuthored": {
      "regions": [
        "North America",
        "Europe (Western)",
        "Europe (Central/Eastern)",
        "UK & Ireland",
        "Oceania",
        "East Asia",
        "South Asia",
        "Southeast Asia",
        "Middle East & North Africa",
        "Sub-Saharan Africa",
        "Latin America & Caribbean",
        "Global/International"
      ],
      "authored": [
        667,
        381,
        63,
        221,
        77,
        149,
        54,
        82,
        92,
        83,
        73,
        1479
      ],
      "affected": [
        755,
        700,
        147,
        317,
        127,
        412,
        164,
        184,
        209,
        179,
        156,
        788
      ]
    },
    "cstCitations": {
      "labels": [
        "Laudato Si'",
        "Fratelli Tutti",
        "Laborem Exercens",
        "Rerum Novarum",
        "Rome Call",
        "Pontifical Academy",
        "Catholic Social Teaching",
        "Centesimus Annus",
        "Caritas in Veritate",
        "Quadragesimo Anno",
        "Mater et Magistra",
        "Gaudium et Spes",
        "Octogesima Adveniens",
        "Evangelii Gaudium",
        "Pacem in Terris",
        "Pope Francis",
        "Holy See",
        "COMECE"
      ],
      "values": [
        2,
        2,
        0,
        2,
        14,
        12,
        12,
        0,
        1,
        0,
        0,
        3,
        0,
        0,
        1,
        29,
        11,
        2
      ]
    },
    "cstByRegion": {
      "regions": [
        "North America",
        "Europe (Western)",
        "Europe (Central/Eastern)",
        "UK & Ireland",
        "Oceania",
        "East Asia",
        "South Asia",
        "Southeast Asia",
        "Middle East & North Africa",
        "Sub-Saharan Africa",
        "Latin America & Caribbean",
        "Global/International"
      ],
      "rates": [
        1.5,
        2.9,
        1.6,
        0.9,
        0.0,
        3.4,
        0.0,
        4.9,
        1.1,
        1.2,
        5.5,
        0.9
      ],
      "counts": [
        10,
        11,
        1,
        2,
        0,
        5,
        0,
        4,
        1,
        1,
        4,
        13
      ]
    },
    "languageBreakdown": {
      "labels": [
        "en",
        "English",
        "Multilingual",
        "Chinese",
        "es",
        "de",
        "ar",
        "fr",
        "pt",
        "zh",
        "Arabic",
        "Korean",
        "Portuguese",
        "ko",
        "Persian"
      ],
      "values": [
        2368,
        165,
        89,
        38,
        36,
        32,
        32,
        30,
        30,
        23,
        23,
        22,
        21,
        19,
        18
      ]
    }
  },
  "annotations": {
    "summary.findings": [
      {
        "perspective": "Labor Policy",
        "text": "The dominance of automation displacement (872 items, 25.4%) and creative/knowledge labor (805 items) as top themes reveals a discourse shaped by acute displacement anxieties rather than structural labor redesign. Session 7 introduced Public Sector AI (278 items) recognizing government workforce transformation as a distinct policy domain; Session 8 reclassified 9 cross-cutting items into creative_knowledge, public_sector_ai, and informal_supply_chains via targeted pattern additions. Meanwhile, content moderation (217 items) and surveillance (200 items) remain severely underrepresented \u2014 these exploitative practices are expanding faster than policy attention can follow."
      },
      {
        "perspective": "CST Perspective",
        "text": "With 52 items citing CST documents across a corpus of 3,444, the Church\u2019s century-long tradition of labor teaching remains underutilized in precisely the policy arena where its principles of worker dignity and the priority of labor over capital are most urgently needed. The expansion from 18 tracked CST sources reveals engagement concentrated around Pope Francis (29 items) and the Rome Call for AI Ethics (14 items), while foundational encyclicals like Laborem Exercens and Centesimus Annus remain largely uncited."
      }
    ],
    "summary.themes": [
      {
        "perspective": "Computational Linguistics",
        "text": "The theme distribution is markedly top-heavy: the top three themes (Automation 25.4%, Creative Knowledge 23.4%, Disability/Accessibility 17.3%) account for over 66% of items. Session 7 added a 17th theme (Public Sector AI & Digital Government, 278 items) and tightened disability classification via context windowing (778\u2192595 items, removing peripheral mentions). Meanwhile surveillance monitoring dropped from 381\u2192200 after bounding legacy patterns that had been scanning entire documents. Content Moderation (217) and Surveillance (200) remain the least-covered themes."
      },
      {
        "perspective": "Labor Policy",
        "text": "The persistent statement-paper gap in Skill Transformation (492 statements vs. 8 papers) exposes a dangerous pattern: policymakers are issuing guidance on workforce reskilling with almost no empirical research base, suggesting that skill transformation rhetoric may function as politically convenient deflection."
      }
    ],
    "summary.acceleration": [
      {
        "perspective": "Regional Studies",
        "text": "The 76.2% post-ChatGPT concentration reveals a reactive, event-driven discourse pattern rather than sustained institutional capacity for AI-labor governance. This temporal clustering raises serious concerns about the Global South\u2019s ability to participate meaningfully: regions with weaker research infrastructure are being asked to respond to a discourse whose terms were set within months by North American and European actors."
      }
    ],
    "heatmap.main": [
      {
        "perspective": "Labor Policy",
        "text": "The intense hotspots at the intersection of Global/International bodies with collective bargaining and automation reveal that supranational organizations are setting the normative framework while regional and national actors follow rather than lead. Despite new MENA and Southeast Asian entries from Session 6 discovery, the persistent thinness in South Asia (52 authored items vs. 163 discussed) and Sub-Saharan Africa (83 authored vs. 168 discussed) remains alarming given these regions contain the largest concentrations of workers most exposed to AI-driven labor displacement."
      },
      {
        "perspective": "Regional Studies",
        "text": "The pattern of Global North regions generating discourse about Global South labor conditions \u2014 without corresponding Southern voice \u2014 reproduces a familiar colonial knowledge asymmetry. The heatmap\u2019s empty cells represent systematically silenced perspectives from communities whose labor practices and social protection needs diverge most sharply from dominant frameworks."
      }
    ],
    "heatmap.gaps": [
      {
        "perspective": "CST Perspective",
        "text": "The empty cells where Just Transition intersects with the Global South represent a profound failure of solidarity \u2014 the principle that the costs of economic transformation must not fall disproportionately on those least responsible and least equipped. The universal destination of goods demands that AI\u2019s benefits be directed toward, not extracted from, these regions."
      }
    ],
    "geographic.concentration": [
      {
        "perspective": "Regional Studies",
        "text": "The treemap\u2019s massive Global/International block confirms that AI-labor governance is being constructed through an extraordinarily narrow geographic lens. International bodies headquartered in Geneva, New York, and Paris amplify perspectives already dominant in their host regions, while Africa, Latin America, and most of Asia remain peripheral."
      },
      {
        "perspective": "Labor Policy",
        "text": "The regional distribution mirrors the geography of AI development rather than AI impact \u2014 a fundamental misalignment. Effective labor policy requires centering the voices of regions where informal employment and weak social protection create fundamentally different AI-labor dynamics."
      }
    ],
    "geographic.language": [
      {
        "perspective": "Computational Linguistics",
        "text": "The overwhelming English-language dominance systematically excludes labor discourse in Mandarin, Spanish, Arabic, Hindi, and Bahasa \u2014 languages spoken by the majority of the global workforce most affected by AI automation. This monolingual bias is epistemological: concepts like \u2018gig work\u2019 and \u2018just transition\u2019 carry fundamentally different meanings across linguistic traditions, and English-only analysis flattens these distinctions."
      }
    ],
    "temporal.emergence": [
      {
        "perspective": "Labor Policy",
        "text": "The sharp inflection at 2023 marks AI-labor discourse shifting from specialist academic concern to mainstream policy emergency. This acceleration has favored themes with existing institutional champions \u2014 collective bargaining backed by unions, automation fears backed by media \u2014 while content moderation and algorithmic management remain on slower growth curves, risking that the policy window closes before these urgent issues achieve critical mass."
      }
    ],
    "temporal.cumulative": [
      {
        "perspective": "Academic Writing",
        "text": "The near-vertical cumulative growth from 2023 is characteristic of a field in its \u2018gold rush\u2019 phase \u2014 rapid output with limited quality control or theoretical consolidation. Historical parallels with bioethics suggest this pace will plateau within 2\u20133 years, making the current moment critical for establishing rigorous methodological standards before the field\u2019s canonical frameworks calcify."
      }
    ],
    "voicegap.authored": [
      {
        "perspective": "Regional Studies",
        "text": "The 3.1x ratio for South Asia \u2014 discussed more than three times as often as it authors \u2014 quantifies epistemic extraction where Global South labor conditions serve as case studies for Global North theorists. East Asia (2.8x), Middle East & North Africa (2.4x), and Southeast Asia (2.2x) follow a similar pattern. This is structural: conference locations, journal gatekeeping, funding flows, and language barriers systematically convert Southern experience into Northern intellectual capital."
      },
      {
        "perspective": "CST Perspective",
        "text": "The preferential option for the poor demands that those most affected by AI\u2019s labor disruptions be heard as primary authors of their own futures. The voice gap reveals a discourse that violates this principle at scale \u2014 treating workers in South and Southeast Asia as objects of analysis rather than subjects of their own agency and dignity."
      }
    ],
    "voicegap.orgtypes": [
      {
        "perspective": "Labor Policy",
        "text": "The organizational composition reveals think tanks and international organizations dominating volume while trade unions, worker cooperatives, and grassroots labor organizations remain marginal contributors. The most influential AI-labor frameworks are being designed by actors at least one institutional remove from the shop floor and the platform algorithm."
      }
    ],
    "voicegap.cst": [
      {
        "perspective": "CST Scholar",
        "text": "CST-citing items cluster around Pope Francis (29 items), Rome Call for AI Ethics (14), and general \u2018Catholic Social Teaching\u2019 references (12), while foundational labor encyclicals \u2014 Laborem Exercens, Centesimus Annus, Caritas in Veritate \u2014 remain nearly uncited. Engagement is personality-driven rather than doctrinally grounded, drawn to papal media presence rather than the systematic social teaching tradition. The regional pattern of CST engagement likely mirrors the Church\u2019s institutional strength rather than the regions where solidarity principles are most operationally needed."
      }
    ]
  }
};
